# Makefile for guides

LAME=lame

.SUFFIXES: .wav .mp3

.wav.mp3:
	$(LAME) $< $@

SOUNDS=escape_the_cave.mp3 \
	game_over.mp3 \
	level_1.mp3 \
	level_2.mp3 \
	level_3.mp3 \
	level_4.mp3 \
	level_5.mp3 \
	level_6.mp3 \
	level_7.mp3 \
	level_8.mp3 \
	level_9.mp3 \
	level_10.mp3 \
	need_key.mp3 \
	normal_mode.mp3 \
	one_minute.mp3 \
	picked_bomb.mp3 \
	picked_compass.mp3 \
	picked_health.mp3 \
	picked_key.mp3 \
	placed_bomb.mp3 \
	press_z.mp3 \
	random_mode.mp3 \
	reached_goal.mp3 \
	ten_seconds.mp3 \
	thirty_seconds.mp3 \
	tutorial_bomb.mp3 \
	tutorial_compass.mp3 \
	tutorial_health.mp3 \
	tutorial_key.mp3 \
	tutorial_move.mp3 \
	tutorial_enemy.mp3 \
	tutorial_trap.mp3 \
	tutorial_time.mp3 \
	twenty_seconds.mp3 \
	you_escaped.mp3

all: $(SOUNDS)

clean:
	-$(RM) $(SOUNDS)

escape_the_cave.mp3: escape_the_cave.wav
game_over.mp3: game_over.wav
level_1.mp3: level_1.wav
level_2.mp3: level_2.wav
level_3.mp3: level_3.wav
level_4.mp3: level_4.wav
level_5.mp3: level_5.wav
level_6.mp3: level_6.wav
level_7.mp3: level_7.wav
level_8.mp3: level_8.wav
level_9.mp3: level_9.wav
level_10.mp3: level_10.wav
need_key.mp3: need_key.wav
normal_mode.mp3: normal_mode.wav
one_minute.mp3: one_minute.wav
picked_bomb.mp3: picked_bomb.wav
picked_compass.mp3: picked_compass.wav
picked_health.mp3: picked_health.wav
picked_key.mp3: picked_key.wav
placed_bomb.mp3: placed_bomb.wav
press_z.mp3: press_z.wav
random_mode.mp3: random_mode.wav
reached_goal.mp3: reached_goal.wav
ten_seconds.mp3: ten_seconds.wav
thirty_seconds.mp3: thirty_seconds.wav
tutorial_bomb.mp3: tutorial_bomb.wav
tutorial_compass.mp3: tutorial_compass.wav
tutorial_health.mp3: tutorial_health.wav
tutorial_key.mp3: tutorial_key.wav
tutorial_move.mp3: tutorial_move.wav
tutorial_enemy.mp3: tutorial_enemy.wav
tutorial_trap.mp3: tutorial_trap.wav
tutorial_time.mp3: tutorial_time.wav
twenty_seconds.mp3: twenty_seconds.wav
you_escaped.mp3: you_escaped.wav

